[en]
  title = "Hugo Zzo Theme"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[ja]
  title = "BAMBi's Blog"
  languageName = "日本語"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/ja"
