[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 5

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 5

[[main]]
  identifier = "presentation"
  name = "Pt"
  url = "presentation"
  weight = 5

[[main]]
 identifier = "posts"
 name = "Posts"
 url = "posts"
 weight = 5

#[[main]]
#  identifier = "publication"
#  name = "Pub"
#  url = "publication"
#  weight = 7
