[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 5

[[main]]
 identifier = "posts"
 name = "Tec"
 url = "posts"
 weight = 5

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 5

[[main]]
  identifier = "publication"
  name = "Life"
  url = "publication"
  weight = 5

