[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 3

[[main]]
 identifier = "posts"
 name = "Tec"
 url = "posts"
 weight = 4

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 5

[[main]]
  identifier = "publication"
  name = "Life"
  url = "publication"
  weight = 7

#[[main]]
#  identifier = "presentation"
#  name = "Pt"
#  url = "presentation"
#  weight = 5
